version: "3.9"

services:
  app:
    build:
      context: ../
      dockerfile: ./build/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - ../.env
  db:
    image: postgres:15
    env_file:
      - ../.env
    ports:
      - "5431:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
